$f = (Resolve-Path "curso-avaliacao/app.js").Path
$enc = [System.Text.Encoding]::UTF8

$extra = @"

CURSO.modulos.push({id:5,titulo:'Prescricao Corretiva',aulas:[
{id:501,titulo:'Protocolo CES: inibir, alongar, ativar, integrar',duracao:'17 min',conteudo:'<h3>Protocolo CES</h3><p>O protocolo CES do NASM e a abordagem mais sistematizada para correcao postural.</p><ol><li><strong>Inibir:</strong> Foam roller nos musculos hiperativos. 30-60s por ponto.</li><li><strong>Alongar:</strong> Alongamento estatico dos musculos encurtados. 20-30s, 2-3 series.</li><li><strong>Ativar:</strong> Exercicios isolados dos musculos inibidos. 10-15 reps lentas.</li><li><strong>Integrar:</strong> Exercicios funcionais globais.</li></ol><div class=destaque>Sempre siga a ordem: inibir, alongar, ativar, integrar.</div>'},
{id:502,titulo:'Exercicios corretivos por regiao',duracao:'20 min',conteudo:'<h3>Exercicios Corretivos</h3><p><strong>Cervical e Ombros:</strong></p><ul><li>Inibir: foam roller em peitoral e trapezio superior</li><li>Alongar: peitoral na porta, inclinacao cervical</li><li>Ativar: chin tuck, rotacao externa com elastico</li><li>Integrar: remada, face pull</li></ul><p><strong>Lombar e Pelve:</strong></p><ul><li>Inibir: foam roller em TFL e iliopsoas</li><li>Alongar: afundo, piriforme</li><li>Ativar: ponte glutea, bird dog</li><li>Integrar: agachamento, deadlift romeno</li></ul>'},
{id:503,titulo:'Periodizacao do treino corretivo',duracao:'12 min',conteudo:'<h3>Periodizacao Corretiva</h3><p>O treino corretivo deve ser periodizado em fases progressivas.</p><div class=tabela-wrap><table><tr><th>Fase</th><th>Duracao</th><th>Foco</th></tr><tr><td>1 - Estabilizacao</td><td>4-6 semanas</td><td>Ativacao e controle motor</td></tr><tr><td>2 - Forca</td><td>4-8 semanas</td><td>Forca dos musculos inibidos</td></tr><tr><td>3 - Potencia</td><td>4-6 semanas</td><td>Integracao funcional</td></tr></table></div><div class=destaque>Reavaliar a cada 4-6 semanas para ajustar o protocolo.</div>'}
],quiz:[
{pergunta:'Qual e a primeira fase do protocolo CES?',opcoes:['Ativar','Alongar','Inibir','Integrar'],correta:2},
{pergunta:'Qual exercicio e indicado para ativar o gluteo maximo?',opcoes:['Leg press','Ponte glutea','Agachamento livre','Cadeira extensora'],correta:1},
{pergunta:'Com que frequencia deve-se reavaliar o protocolo corretivo?',opcoes:['A cada 2 semanas','A cada 4-6 semanas','A cada 6 meses','Apenas no inicio'],correta:1}
]});

CURSO.modulos.push({id:6,titulo:'Laudo e Relatorio Profissional',aulas:[
{id:601,titulo:'Como estruturar um laudo postural',duracao:'15 min',conteudo:'<h3>Estrutura do Laudo Postural</h3><p>O laudo postural e o documento que formaliza os achados da avaliacao. Deve ser claro, objetivo e tecnicamente embasado.</p><p><strong>Estrutura basica:</strong></p><ol><li>Identificacao do avaliado (nome, idade, data)</li><li>Objetivo da avaliacao</li><li>Metodologia utilizada</li><li>Achados posturais por vista</li><li>Achados funcionais (testes)</li><li>Hipoteses de disfuncao muscular</li><li>Recomendacoes e encaminhamentos</li><li>Assinatura e CREF do profissional</li></ol><div class=alerta>O laudo nao e diagnostico medico. Use termos como hipotese, sugere, indica, observado.</div>'},
{id:602,titulo:'Linguagem tecnica e termos corretos',duracao:'10 min',conteudo:'<h3>Linguagem Tecnica</h3><div class=tabela-wrap><table><tr><th>Evitar</th><th>Usar</th></tr><tr><td>Tem escoliose</td><td>Observa-se desvio lateral da coluna</td></tr><tr><td>Musculo fraco</td><td>Musculo possivelmente inibido</td></tr><tr><td>Problema no joelho</td><td>Valgo dinamico de joelho observado no agachamento</td></tr><tr><td>Postura errada</td><td>Desvio postural identificado</td></tr></table></div><div class=destaque>A linguagem correta protege o profissional legalmente e demonstra competencia tecnica.</div>'},
{id:603,titulo:'Apresentacao dos resultados ao aluno',duracao:'12 min',conteudo:'<h3>Apresentacao ao Aluno</h3><p>A forma como voce apresenta os resultados impacta diretamente na adesao do aluno ao programa.</p><ul><li>Use linguagem acessivel, sem jargoes tecnicos excessivos</li><li>Mostre os pontos positivos antes dos negativos</li><li>Use imagens e referencias visuais quando possivel</li><li>Explique o que cada achado significa na pratica do dia a dia</li><li>Apresente o plano de acao de forma clara e motivadora</li></ul><div class=destaque>O aluno que entende sua avaliacao tem muito mais chances de seguir o programa.</div>'}
],quiz:[
{pergunta:'O laudo postural pode conter diagnostico de doencas?',opcoes:['Sim, sempre','Sim, se o profissional tiver especializacao','Nao, apenas observacoes funcionais','Apenas com autorizacao medica'],correta:2},
{pergunta:'Qual termo e mais adequado no laudo?',opcoes:['Tem escoliose','Desvio lateral da coluna observado','Coluna torta','Problema na coluna'],correta:1},
{pergunta:'Qual e o primeiro passo ao apresentar resultados ao aluno?',opcoes:['Mostrar os problemas encontrados','Mostrar os pontos positivos antes','Entregar o laudo sem explicar','Encaminhar ao medico'],correta:1}
]});

CURSO.modulos.push({id:7,titulo:'Pratica Profissional e Mercado',aulas:[
{id:701,titulo:'Montando seu protocolo de avaliacao',duracao:'18 min',conteudo:'<h3>Montando seu Protocolo</h3><p>Um protocolo padronizado garante consistencia, profissionalismo e protecao legal.</p><p><strong>Checklist do protocolo completo:</strong></p><ul><li>Ficha de anamnese e PAR-Q assinados</li><li>Termo de consentimento informado</li><li>Medicoes antropometricas (peso, altura, circunferencias)</li><li>Dobras cutaneas (protocolo escolhido)</li><li>Avaliacao postural nas 4 vistas</li><li>Testes funcionais (overhead squat, single leg squat)</li><li>Testes de aptidao (forca, flexibilidade, cardio)</li><li>Laudo escrito e assinado</li><li>Apresentacao ao aluno</li><li>Agendamento da reavaliacao</li></ul>'},
{id:702,titulo:'Precificacao e posicionamento no mercado',duracao:'14 min',conteudo:'<h3>Precificacao e Mercado</h3><p>A avaliacao fisica e postural e um diferencial competitivo poderoso. Profissionais que avaliam cobram mais e reteem mais alunos.</p><p><strong>Modelos de precificacao:</strong></p><ul><li>Avaliacao inclusa no pacote de treino</li><li>Avaliacao como servico separado (R$150-400)</li><li>Pacote avaliacao + laudo + plano corretivo</li><li>Reavaliacao trimestral como fidelizacao</li></ul><div class=destaque>Documente tudo. A evolucao mensuravel e seu maior argumento de venda.</div>'},
{id:703,titulo:'Casos praticos e estudos de caso',duracao:'20 min',conteudo:'<h3>Casos Praticos</h3><p><strong>Caso 1 - Aluno com dor lombar:</strong> Homem, 35 anos, sedentario, queixa de dor lombar cronica. Avaliacao: anteroversao pelvica, hiperlordose lombar, valgo de joelho. Testes: iliopsoas encurtado, gluteo inibido. Protocolo: inibir TFL e eretor, alongar iliopsoas, ativar gluteo, integrar com agachamento.</p><p><strong>Caso 2 - Atleta com dor no ombro:</strong> Mulher, 28 anos, pratica crossfit. Avaliacao: protracao de ombro, hipercifose toracica. Testes: peitoral encurtado, trapezio medio inibido. Protocolo: inibir peitoral, alongar peitoral na porta, ativar trapezio medio com elastico, integrar com remada.</p><div class=destaque>Cada caso e unico. O protocolo deve ser individualizado com base nos achados da avaliacao.</div>'}
],quiz:[
{pergunta:'Qual documento deve ser assinado antes da avaliacao?',opcoes:['Apenas a ficha de anamnese','PAR-Q e termo de consentimento','Somente o laudo','Nenhum documento e necessario'],correta:1},
{pergunta:'Qual e o principal beneficio de documentar a evolucao do aluno?',opcoes:['Cumprir obrigacao legal','Argumento de venda e fidelizacao','Facilitar encaminhamentos','Reduzir o tempo de atendimento'],correta:1},
{pergunta:'No caso de dor lombar com anteroversao pelvica, qual musculo deve ser ativado?',opcoes:['Iliopsoas','Eretor da espinha','Gluteo maximo','Reto femoral'],correta:2}
]});
"@

[System.IO.File]::AppendAllText($f, $extra, $enc)
Write-Output "Modulos 5, 6 e 7 adicionados com sucesso!"
