$f = (Resolve-Path "curso-avaliacao/app.js").Path
$enc = [System.Text.Encoding]::UTF8

# Ler o arquivo atual e pegar apenas as primeiras 75 linhas (config + funcoes)
$lines = Get-Content $f
$base = $lines[0..74] -join "`n"

# Reescrever com base limpa + modulos corretos
$modulos = @"

var CURSO = { nome: 'Avaliacao Fisica e Postural Profissional', modulos: [] };

CURSO.modulos.push({id:1,titulo:'Fundamentos da Avaliacao Fisica',aulas:[
{id:101,titulo:'O que e avaliacao fisica e por que fazer',duracao:'12 min',conteudo:'<h3>O que e avaliacao fisica</h3><p>A avaliacao fisica e o conjunto de procedimentos que permitem ao profissional conhecer o estado atual do individuo, identificar riscos e prescrever exercicios com seguranca.</p><div class=destaque>Sem avaliacao a prescricao e baseada em suposicoes. Com avaliacao e baseada em evidencias.</div><ul><li>Identificar fatores de risco cardiovascular</li><li>Estabelecer linha de base para comparacao futura</li><li>Personalizar a prescricao de exercicios</li><li>Motivar o aluno mostrando evolucao mensuravel</li><li>Proteger o profissional legalmente</li></ul>'},
{id:102,titulo:'Etica e responsabilidade profissional',duracao:'10 min',conteudo:'<h3>Etica Profissional</h3><p>O profissional de Educacao Fisica tem responsabilidade legal e etica sobre os procedimentos que realiza.</p><div class=alerta>O profissional de EF nao diagnostica doencas. Ele identifica alteracoes funcionais e encaminha ao medico quando necessario.</div><ul><li>CREF: registro obrigatorio para atuar legalmente</li><li>Sigilo: dados do aluno sao confidenciais</li><li>Consentimento: termo deve ser assinado antes da avaliacao</li><li>Encaminhamento: saber quando encaminhar ao medico</li></ul>'},
{id:103,titulo:'Anamnese completa: o que perguntar',duracao:'15 min',conteudo:'<h3>Anamnese Completa</h3><p>A anamnese e a entrevista inicial com o aluno. E o primeiro e mais importante passo da avaliacao.</p><div class=tabela-wrap><table><tr><th>Categoria</th><th>O que investigar</th></tr><tr><td>Historico medico</td><td>Doencas cronicas, cirurgias, medicamentos</td></tr><tr><td>Atividade fisica</td><td>Experiencia anterior, frequencia, modalidades</td></tr><tr><td>Queixas e dores</td><td>Localizacao, intensidade, frequencia</td></tr><tr><td>Objetivos</td><td>Emagrecimento, hipertrofia, saude</td></tr><tr><td>Habitos de vida</td><td>Sono, alimentacao, estresse</td></tr></table></div>'},
{id:104,titulo:'PAR-Q e triagem de risco cardiovascular',duracao:'14 min',conteudo:'<h3>PAR-Q</h3><p>O PAR-Q e um questionario de 7 perguntas que identifica se o individuo precisa de liberacao medica antes de iniciar atividade fisica.</p><ul><li>Algum medico ja disse que voce tem problema cardiaco?</li><li>Voce sente dor no peito ao praticar atividade fisica?</li><li>Voce perdeu o equilibrio por tontura?</li><li>Voce tem algum problema osseo ou articular?</li><li>Seu medico prescreveu medicamento para pressao?</li></ul><div class=alerta>Se qualquer resposta for SIM, encaminhe ao medico antes de iniciar.</div>'}
],quiz:[
{pergunta:'Qual o principal objetivo da avaliacao fisica?',opcoes:['Diagnosticar doencas','Conhecer o estado atual e prescrever com seguranca','Substituir a consulta medica','Apenas motivar o aluno'],correta:1},
{pergunta:'O PAR-Q e utilizado para:',opcoes:['Medir composicao corporal','Avaliar postura','Triagem de risco cardiovascular','Calcular o VO2 maximo'],correta:2},
{pergunta:'Quantas perguntas tem o PAR-Q?',opcoes:['5','6','7','10'],correta:2}
]});

CURSO.modulos.push({id:2,titulo:'Composicao Corporal',aulas:[
{id:201,titulo:'Massa magra, gordura e agua corporal',duracao:'13 min',conteudo:'<h3>Composicao Corporal</h3><p>A composicao corporal descreve as proporcoes dos diferentes componentes do corpo humano: massa magra, gordura corporal e agua corporal.</p><div class=destaque>Modelo de 2 compartimentos: divide o corpo em massa gorda e massa livre de gordura (MLG).</div><div class=tabela-wrap><table><tr><th>Componente</th><th>Homens</th><th>Mulheres</th></tr><tr><td>Gordura essencial</td><td>2-5%</td><td>10-13%</td></tr><tr><td>Atletico</td><td>6-13%</td><td>14-20%</td></tr><tr><td>Fitness</td><td>14-17%</td><td>21-24%</td></tr><tr><td>Aceitavel</td><td>18-24%</td><td>25-31%</td></tr><tr><td>Obesidade</td><td>25%+</td><td>32%+</td></tr></table></div>'},
{id:202,titulo:'Dobras cutaneas: protocolo e tecnica',duracao:'18 min',conteudo:'<h3>Dobras Cutaneas</h3><p>A adipometria por dobras cutaneas e o metodo mais utilizado na pratica. Requer treinamento e padronizacao para resultados confiaveis.</p><div class=alerta>Regra de ouro: sempre use o mesmo protocolo, avaliador e adipometro nas reavaliações.</div><ol><li>Marque o ponto anatomico com caneta dermografica</li><li>Pegue a dobra com polegar e indicador, 1cm acima do ponto</li><li>Aplique o adipometro perpendicular a dobra</li><li>Aguarde 2 segundos e leia</li><li>Repita 3 vezes e use a mediana</li></ol>'},
{id:203,titulo:'Protocolos: Jackson-Pollock, Guedes, Faulkner',duracao:'16 min',conteudo:'<h3>Protocolos de Estimativa de Gordura</h3><div class=tabela-wrap><table><tr><th>Protocolo</th><th>Dobras</th><th>Populacao</th></tr><tr><td>Jackson-Pollock 7</td><td>Peitoral, Axilar, Tricipital, Subescapular, Abdominal, Suprailiaca, Coxa</td><td>Adultos geral</td></tr><tr><td>JP 3 Homens</td><td>Peitoral, Abdominal, Coxa</td><td>Homens</td></tr><tr><td>JP 3 Mulheres</td><td>Tricipital, Suprailiaca, Coxa</td><td>Mulheres</td></tr><tr><td>Guedes</td><td>Tricipital, Subescapular, Suprailiaca</td><td>Brasileiros</td></tr><tr><td>Faulkner</td><td>Tricipital, Subescapular, Suprailiaca, Abdominal</td><td>Atletas</td></tr></table></div>'},
{id:204,titulo:'IMC, circunferencias e relacao cintura-quadril',duracao:'12 min',conteudo:'<h3>Indices Antropometricos</h3><p><strong>IMC:</strong> Peso(kg) / Altura(m)^2</p><div class=tabela-wrap><table><tr><th>IMC</th><th>Classificacao</th></tr><tr><td>Abaixo de 18,5</td><td>Abaixo do peso</td></tr><tr><td>18,5-24,9</td><td>Peso normal</td></tr><tr><td>25,0-29,9</td><td>Sobrepeso</td></tr><tr><td>30,0-34,9</td><td>Obesidade I</td></tr><tr><td>40+</td><td>Obesidade III</td></tr></table></div><div class=alerta>O IMC nao diferencia massa muscular de gordura.</div>'}
],quiz:[
{pergunta:'Qual protocolo e mais indicado para brasileiros?',opcoes:['Faulkner','Jackson-Pollock 7','Guedes','Durnin-Womersley'],correta:2},
{pergunta:'O IMC e calculado por:',opcoes:['Peso/Altura','Peso/Altura ao quadrado','Altura/Peso','Circunferencia/Altura'],correta:1},
{pergunta:'Risco de circunferencia abdominal para mulheres:',opcoes:['Acima de 80cm','Acima de 90cm','Acima de 70cm','Acima de 100cm'],correta:0}
]});

CURSO.modulos.push({id:3,titulo:'Avaliacao Postural',aulas:[
{id:301,titulo:'Postura ideal e desvios posturais',duracao:'15 min',conteudo:'<h3>Postura Ideal e Desvios Posturais</h3><p>A postura ideal e aquela em que o alinhamento dos segmentos corporais minimiza o estresse sobre estruturas passivas e o trabalho muscular necessario.</p><div class=destaque>Linha de prumo lateral: lobulo da orelha, processo acromio, grande trocanter, ligeiramente anterior ao joelho e ao maleo lateral.</div><ul><li>Hiperlordose cervical: aumento da curvatura cervical</li><li>Hipercifose toracica: aumento da curvatura toracica</li><li>Hiperlordose lombar: aumento da curvatura lombar</li><li>Escoliose: desvio lateral da coluna</li><li>Anteroversao pelvica: pelve inclinada para frente</li></ul>'},
{id:302,titulo:'Avaliacao nas 4 vistas',duracao:'20 min',conteudo:'<h3>Avaliacao nas 4 Vistas</h3><p><strong>Vista Anterior:</strong> alinhamento da cabeca, nivel dos ombros, cristas iliacas, joelhos (valgo/varo), pe (pronado/supinado).</p><p><strong>Vista Posterior:</strong> alinhamento da coluna (escoliose), nivel das escapulas, nivel dos gluteos, eixo do calcaneo.</p><p><strong>Vista Lateral:</strong> posicao da cabeca, curvaturas cervical/toracica/lombar, posicao do ombro, posicao da pelve, joelho.</p><div class=alerta>Avalie o aluno em roupas adequadas para visualizar os pontos anatomicos.</div>'},
{id:303,titulo:'Testes funcionais: overhead squat e single leg squat',duracao:'18 min',conteudo:'<h3>Testes Funcionais</h3><p><strong>Overhead Squat:</strong> Pes na largura dos ombros, bracos elevados, agachar ate 90 graus. Observe: queda dos bracos, inclinacao do tronco, valgo dos joelhos, elevacao dos calcanhares.</p><p><strong>Single Leg Squat:</strong> Apoio em um pe, agachar ate 45 graus. Observe: valgo do joelho, inclinacao lateral do tronco, queda da pelve (sinal de Trendelenburg).</p><div class=destaque>Os testes funcionais guiam a prescricao corretiva com muito mais precisao que a avaliacao estatica isolada.</div>'},
{id:304,titulo:'Sindrome cruzada de Janda',duracao:'14 min',conteudo:'<h3>Sindrome Cruzada de Janda</h3><p><strong>Sindrome Cruzada Superior:</strong> Encurtados: peitoral menor, trapezio superior, elevador da escapula. Inibidos: flexores profundos do pescoco, trapezio medio/inferior. Resultado: protracao de cabeca e ombros.</p><p><strong>Sindrome Cruzada Inferior:</strong> Encurtados: iliopsoas, reto femoral, TFL, eretor lombar. Inibidos: gluteo maximo, abdominais profundos. Resultado: anteroversao pelvica e hiperlordose lombar.</p><div class=destaque>Identificar o padrao de Janda permite criar um protocolo corretivo sistematico.</div>'}
],quiz:[
{pergunta:'Na sindrome cruzada inferior, qual musculo tipicamente esta inibido?',opcoes:['Iliopsoas','Reto femoral','Gluteo maximo','Eretor da espinha'],correta:2},
{pergunta:'O overhead squat avalia principalmente:',opcoes:['Forca maxima','Padroes de movimento e disfuncoes','Composicao corporal','Flexibilidade isolada'],correta:1},
{pergunta:'A anteroversao pelvica esta associada a:',opcoes:['Hipercifose toracica','Hiperlordose lombar','Escoliose','Retroversao cervical'],correta:1}
]});

CURSO.modulos.push({id:4,titulo:'Testes de Aptidao Fisica',aulas:[
{id:401,titulo:'Teste de forca: 1RM e repeticoes maximas',duracao:'16 min',conteudo:'<h3>Avaliacao de Forca</h3><p><strong>Teste de 1RM:</strong> Carga maxima que o individuo consegue mover em uma unica repeticao com tecnica correta. Protocolo: aquecimento, tentativas progressivas com 3-5 min de descanso.</p><div class=alerta>Contraindicado para iniciantes, idosos e pessoas com historico cardiovascular.</div><div class=tabela-wrap><table><tr><th>Reps</th><th>% 1RM</th></tr><tr><td>1</td><td>100%</td></tr><tr><td>5</td><td>87%</td></tr><tr><td>10</td><td>75%</td></tr><tr><td>15</td><td>65%</td></tr></table></div>'},
{id:402,titulo:'Teste de flexibilidade: banco de Wells e goniometria',duracao:'12 min',conteudo:'<h3>Avaliacao de Flexibilidade</h3><p><strong>Banco de Wells:</strong> Avalia flexibilidade de isquiotibiais e lombar. Sentado com joelhos estendidos, empurrar a regua o maximo possivel.</p><div class=tabela-wrap><table><tr><th>Classificacao</th><th>Homens</th><th>Mulheres</th></tr><tr><td>Excelente</td><td>maior 38cm</td><td>maior 41cm</td></tr><tr><td>Bom</td><td>34-38cm</td><td>37-41cm</td></tr><tr><td>Regular</td><td>25-33cm</td><td>28-36cm</td></tr><tr><td>Fraco</td><td>menor 25cm</td><td>menor 28cm</td></tr></table></div>'},
{id:403,titulo:'Teste cardiorrespiratorio: Cooper e step test',duracao:'14 min',conteudo:'<h3>Avaliacao Cardiorrespiratoria</h3><p><strong>Teste de Cooper (12 min):</strong> Correr/caminhar o maximo de distancia em 12 minutos. VO2max estimado = (distancia em metros - 504,9) / 44,73.</p><p><strong>Step Test de 3 minutos:</strong> Subir e descer um step de 30cm por 3 minutos a 96 bpm. Medir FC apos 1 minuto de recuperacao.</p><div class=destaque>Para populacao sedentaria e idosos, prefira o step test ou o teste de caminhada de 6 minutos.</div>'},
{id:404,titulo:'Interpretacao e classificacao dos resultados',duracao:'13 min',conteudo:'<h3>Interpretacao dos Resultados</h3><p>Apos coletar todos os dados, o profissional deve interpretar os resultados de forma integrada, nao isolada.</p><div class=destaque>Um resultado isolado tem pouco valor. O conjunto dos dados e que revela o perfil real do avaliado.</div><ol><li>Compare cada resultado com os valores de referencia para sexo e idade</li><li>Identifique os pontos criticos</li><li>Cruze os dados posturais com os funcionais</li><li>Considere o historico clinico e os objetivos do aluno</li><li>Priorize as intervencoes por ordem de risco e impacto</li></ol>'}
],quiz:[
{pergunta:'Qual teste avalia flexibilidade de isquiotibiais?',opcoes:['Cooper','Banco de Wells','1RM','Step Test'],correta:1},
{pergunta:'O teste de Cooper dura:',opcoes:['6 minutos','10 minutos','12 minutos','15 minutos'],correta:2},
{pergunta:'Para populacao sedentaria, qual teste cardio e mais indicado?',opcoes:['Cooper','1RM','Step Test ou caminhada de 6 min','Teste de Wingate'],correta:2}
]});

CURSO.modulos.push({id:5,titulo:'Prescricao Corretiva',aulas:[
{id:501,titulo:'Protocolo CES: inibir, alongar, ativar, integrar',duracao:'17 min',conteudo:'<h3>Protocolo CES</h3><p>O protocolo CES do NASM e a abordagem mais sistematizada para correcao postural e funcional.</p><ol><li><strong>Inibir:</strong> Foam roller nos musculos hiperativos. 30-60s por ponto.</li><li><strong>Alongar:</strong> Alongamento estatico dos musculos encurtados. 20-30s, 2-3 series.</li><li><strong>Ativar:</strong> Exercicios isolados dos musculos inibidos. 10-15 reps lentas.</li><li><strong>Integrar:</strong> Exercicios funcionais globais.</li></ol><div class=destaque>Sempre siga a ordem: inibir, alongar, ativar, integrar.</div>'},
{id:502,titulo:'Exercicios corretivos por regiao',duracao:'20 min',conteudo:'<h3>Exercicios Corretivos</h3><p><strong>Cervical e Ombros:</strong></p><ul><li>Inibir: foam roller em peitoral e trapezio superior</li><li>Alongar: peitoral na porta, inclinacao cervical</li><li>Ativar: chin tuck, rotacao externa com elastico</li><li>Integrar: remada, face pull</li></ul><p><strong>Lombar e Pelve:</strong></p><ul><li>Inibir: foam roller em TFL e iliopsoas</li><li>Alongar: afundo, piriforme</li><li>Ativar: ponte glutea, bird dog</li><li>Integrar: agachamento, deadlift romeno</li></ul>'},
{id:503,titulo:'Periodizacao do treino corretivo',duracao:'12 min',conteudo:'<h3>Periodizacao Corretiva</h3><div class=tabela-wrap><table><tr><th>Fase</th><th>Duracao</th><th>Foco</th></tr><tr><td>1 - Estabilizacao</td><td>4-6 semanas</td><td>Ativacao e controle motor</td></tr><tr><td>2 - Forca</td><td>4-8 semanas</td><td>Forca dos musculos inibidos</td></tr><tr><td>3 - Potencia</td><td>4-6 semanas</td><td>Integracao funcional</td></tr></table></div><div class=destaque>Reavaliar a cada 4-6 semanas para ajustar o protocolo.</div>'}
],quiz:[
{pergunta:'Qual e a primeira fase do protocolo CES?',opcoes:['Ativar','Alongar','Inibir','Integrar'],correta:2},
{pergunta:'Qual exercicio e indicado para ativar o gluteo maximo?',opcoes:['Leg press','Ponte glutea','Agachamento livre','Cadeira extensora'],correta:1},
{pergunta:'Com que frequencia deve-se reavaliar o protocolo corretivo?',opcoes:['A cada 2 semanas','A cada 4-6 semanas','A cada 6 meses','Apenas no inicio'],correta:1}
]});

CURSO.modulos.push({id:6,titulo:'Laudo e Relatorio Profissional',aulas:[
{id:601,titulo:'Como estruturar um laudo postural',duracao:'15 min',conteudo:'<h3>Estrutura do Laudo Postural</h3><p>O laudo postural e o documento que formaliza os achados da avaliacao. Deve ser claro, objetivo e tecnicamente embasado.</p><ol><li>Identificacao do avaliado</li><li>Objetivo da avaliacao</li><li>Metodologia utilizada</li><li>Achados posturais por vista</li><li>Achados funcionais</li><li>Hipoteses de disfuncao muscular</li><li>Recomendacoes e encaminhamentos</li><li>Assinatura e CREF do profissional</li></ol><div class=alerta>O laudo nao e diagnostico medico. Use termos como: hipotese, sugere, indica, observado.</div>'},
{id:602,titulo:'Linguagem tecnica e termos corretos',duracao:'10 min',conteudo:'<h3>Linguagem Tecnica</h3><div class=tabela-wrap><table><tr><th>Evitar</th><th>Usar</th></tr><tr><td>Tem escoliose</td><td>Observa-se desvio lateral da coluna</td></tr><tr><td>Musculo fraco</td><td>Musculo possivelmente inibido</td></tr><tr><td>Problema no joelho</td><td>Valgo dinamico de joelho observado no agachamento</td></tr><tr><td>Postura errada</td><td>Desvio postural identificado</td></tr></table></div>'},
{id:603,titulo:'Apresentacao dos resultados ao aluno',duracao:'12 min',conteudo:'<h3>Apresentacao ao Aluno</h3><ul><li>Use linguagem acessivel, sem jargoes tecnicos excessivos</li><li>Mostre os pontos positivos antes dos negativos</li><li>Use imagens e referencias visuais quando possivel</li><li>Explique o que cada achado significa na pratica do dia a dia</li><li>Apresente o plano de acao de forma clara e motivadora</li></ul><div class=destaque>O aluno que entende sua avaliacao tem muito mais chances de seguir o programa.</div>'}
],quiz:[
{pergunta:'O laudo postural pode conter diagnostico de doencas?',opcoes:['Sim, sempre','Sim, com especializacao','Nao, apenas observacoes funcionais','Apenas com autorizacao medica'],correta:2},
{pergunta:'Qual termo e mais adequado no laudo?',opcoes:['Tem escoliose','Desvio lateral da coluna observado','Coluna torta','Problema na coluna'],correta:1},
{pergunta:'Qual e o primeiro passo ao apresentar resultados ao aluno?',opcoes:['Mostrar os problemas encontrados','Mostrar os pontos positivos antes','Entregar o laudo sem explicar','Encaminhar ao medico'],correta:1}
]});

CURSO.modulos.push({id:7,titulo:'Pratica Profissional e Mercado',aulas:[
{id:701,titulo:'Montando seu protocolo de avaliacao',duracao:'18 min',conteudo:'<h3>Montando seu Protocolo</h3><p>Um protocolo padronizado garante consistencia, profissionalismo e protecao legal.</p><ul><li>Ficha de anamnese e PAR-Q assinados</li><li>Termo de consentimento informado</li><li>Medicoes antropometricas</li><li>Dobras cutaneas</li><li>Avaliacao postural nas 4 vistas</li><li>Testes funcionais</li><li>Testes de aptidao</li><li>Laudo escrito e assinado</li><li>Apresentacao ao aluno</li><li>Agendamento da reavaliacao</li></ul>'},
{id:702,titulo:'Precificacao e posicionamento no mercado',duracao:'14 min',conteudo:'<h3>Precificacao e Mercado</h3><p>A avaliacao fisica e postural e um diferencial competitivo poderoso. Profissionais que avaliam cobram mais e reteem mais alunos.</p><ul><li>Avaliacao inclusa no pacote de treino</li><li>Avaliacao como servico separado (R$150-400)</li><li>Pacote avaliacao + laudo + plano corretivo</li><li>Reavaliacao trimestral como fidelizacao</li></ul><div class=destaque>Documente tudo. A evolucao mensuravel e seu maior argumento de venda.</div>'},
{id:703,titulo:'Casos praticos e estudos de caso',duracao:'20 min',conteudo:'<h3>Casos Praticos</h3><p><strong>Caso 1 - Dor lombar:</strong> Homem, 35 anos, sedentario. Avaliacao: anteroversao pelvica, hiperlordose lombar. Protocolo: inibir TFL e eretor, alongar iliopsoas, ativar gluteo, integrar com agachamento.</p><p><strong>Caso 2 - Dor no ombro:</strong> Mulher, 28 anos, crossfit. Avaliacao: protracao de ombro, hipercifose toracica. Protocolo: inibir peitoral, alongar peitoral na porta, ativar trapezio medio, integrar com remada.</p><div class=destaque>Cada caso e unico. O protocolo deve ser individualizado com base nos achados da avaliacao.</div>'}
],quiz:[
{pergunta:'Qual documento deve ser assinado antes da avaliacao?',opcoes:['Apenas a ficha de anamnese','PAR-Q e termo de consentimento','Somente o laudo','Nenhum documento'],correta:1},
{pergunta:'Qual e o principal beneficio de documentar a evolucao do aluno?',opcoes:['Cumprir obrigacao legal','Argumento de venda e fidelizacao','Facilitar encaminhamentos','Reduzir o tempo de atendimento'],correta:1},
{pergunta:'No caso de dor lombar com anteroversao pelvica, qual musculo deve ser ativado?',opcoes:['Iliopsoas','Eretor da espinha','Gluteo maximo','Reto femoral'],correta:2}
]});
"@

$newContent = $base + "`n" + $modulos
[System.IO.File]::WriteAllText($f, $newContent, $enc)
Write-Output "Arquivo reescrito com sucesso! Linhas: $($newContent.Split("`n").Count)"
